# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'LocalSonarQube'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'weather_project'
      cliProjectName: 'weather_project'
      cliSources: 'src'
      extraProperties: |
        sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        sonar.java.binaries=target/classes

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'Path'
      jdkDirectory: '/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: SonarQubeAnalyze@5

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'
